quarkus.devservices.enabled=false

camel.component.kafka.brokers=oravm05:9092

camel.component.aws2-s3.access-key=sa5LRiJPHXrsoP0X8S8J
camel.component.aws2-s3.secret-key=5K8ukYeg2uRvYUzqbBziM6AmYgkgZ4JvsfxASRoe
camel.component.aws2-s3.uri-endpoint-override=http://oravm05:9000
camel.component.aws2-s3.override-endpoint=true
camel.component.aws2-s3.region=us-east-1
camel.component.aws2-s3.force-path-style=true
#camel.component.aws2-s3.bridge-error-handler=true

# Source Database Configuration
quarkus.datasource.db-kind = postgresql
quarkus.datasource.jdbc.url = jdbc:postgresql://oravm05:5432/postgres
quarkus.datasource.username = postgres
quarkus.datasource.password = postgres

sftp.sender.consumersCount=10
# 10 min.
sftp.sender.maxPollIntervalMs=600000
sftp.sender.maximumReconnectAttempts=3
sftp.sender.reconnectDelay=5000

# this setting is for all kafka consumers!
#camel.component.kafka.max-poll-interval-ms = 60000
#camel.component.kafka.max-poll-records = 1
#camel.component.kafka.consumers-count = 10

